language: ruby
rvm:
  - 2.2
script:
  - chmod +x scripts/build
  - ./scripts/build
after_success:
  - chmod +x scripts/deploy
  - ./scripts/deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
