language: ruby
rvm:
  - 2.2.2
install:
  - gem install activesupport 
  - gem install html-proof
  - gem install jekyll
script:
  - chmod +x scripts/build
  - ./scripts/build
after_success:
  - chmod +x scripts/deploy
  - ./scripts/deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
