language: ruby
rvm:
  - 2.2.2
install:
  - gem install activesupport 
  - gem install html-proofer
  - gem install jekyll
  - bundle install
script:
  - chmod +x scripts/build
  - ./scripts/build 
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_deploy: 
  - chmod +x scripts/before_deploy
  - ./scripts/before_deploy 
deploy:
  skip_cleanup: true
  file_glob: true
  file: "build/distributions/worktrail-app-hub-sync*.zip"
  provider: azure_web_apps
  verbose: true
  