language: ruby
rvm:
  - 2.2.2
install:
  - gem install activesupport 
  - gem install html-proofer
  - gem install jekyll
  - bundle install
script:
  - chmod +x scripts/build
  - ./scripts/build 
  - cd /home/travis/build/cmart89/git/_site/
  - echo $PWD
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  skip_cleanup: true 
  provider: azure_web_apps
  verbose: true