language: ruby
rvm:
  - 2.2.2
install:
  - gem install activesupport 
  - gem install html-proofer
  - gem install jekyll
  - bundle install
script:
  - chmod +x scripts/build
  - ./scripts/build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_deploy: 
  - cd $TRAVIS_BUILD_DIR/site/
deploy:
  skip_cleanup: true
  file: _site/
  provider: azure_web_apps
  verbose: true