#!/bin/sh
setup_git() {
  git config --global user.email "chrismartin1989@gmail.com"
  git config --global user.name "cmart89"
}

commit_website_files() {
  git add . 
  git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
}

upload_files() {
  git push https://cmart89:28aaae0172be472cf4162691d3afa12ead23fd9c@github.com/cmart89/build.git head:master> /dev/null 2>&1
}

setup_git
commit_website_files
upload_files	